#!/usr/bin/env node
/**
 * Detects this Mac's Wi‑Fi/LAN IPv4 and writes constants/localSupabaseHost.ts
 * so Expo can reach local Supabase from a physical device on the same network.
 */
import { execSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { networkInterfaces } from 'os';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const OUT_FILE = join(ROOT, 'constants', 'localSupabaseHost.ts');
const DEFAULTS_FILE = join(ROOT, 'constants', 'localSupabaseHost.defaults.ts');
const API_PORT = 54321;

/** macOS Wi‑Fi / Ethernet interface names (en0 is usually Wi‑Fi). */
const PREFERRED_INTERFACES = ['en0', 'en1', 'en2'];

function getIpFromIpconfig(iface) {
  try {
    const ip = execSync(`ipconfig getifaddr ${iface}`, { encoding: 'utf8' }).trim();
    if (/^\d{1,3}(\.\d{1,3}){3}$/.test(ip)) return ip;
  } catch {
    // interface down or unavailable
  }
  return null;
}

/** Prefer active Wi‑Fi (en0) on macOS, then any non-internal en* IPv4. */
export function getMacLanIp() {
  if (process.platform === 'darwin') {
    for (const iface of PREFERRED_INTERFACES) {
      const ip = getIpFromIpconfig(iface);
      if (ip) return ip;
    }
  }

  const nets = networkInterfaces();
  const candidates = [];

  for (const [name, addrs] of Object.entries(nets)) {
    if (name === 'lo0' || name.startsWith('utun') || name.startsWith('awdl')) continue;

    for (const net of addrs ?? []) {
      if (net.family !== 'IPv4' || net.internal) continue;
      if (!/^en\d+$/.test(name) && process.platform === 'darwin') continue;
      candidates.push({ name, address: net.address });
    }
  }

  const en0 = candidates.find((c) => c.name === 'en0');
  if (en0) return en0.address;

  return candidates[0]?.address ?? '127.0.0.1';
}

export function syncLanHost({ quiet = false } = {}) {
  const host = getMacLanIp();
  const url = `http://${host}:${API_PORT}`;

  const contents = `// Auto-generated by scripts/lan-host.mjs — do not edit
// Updated when your Mac's LAN IP changes (Wi‑Fi, etc.)
export const LOCAL_SUPABASE_HOST = '${host}';
export const LOCAL_SUPABASE_API_URL = '${url}';
`;

  if (!existsSync(OUT_FILE) && existsSync(DEFAULTS_FILE)) {
    writeFileSync(OUT_FILE, readFileSync(DEFAULTS_FILE, 'utf8'), 'utf8');
  }

  const previous = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, 'utf8') : '';
  const changed = previous !== contents;

  if (changed) {
    writeFileSync(OUT_FILE, contents, 'utf8');
    if (!quiet) {
      console.log(`[lan-host] Local Supabase API → ${url}`);
    }
  }

  return { host, url, changed };
}

export function startLanWatch({ intervalMs = 3000, quiet = false } = {}) {
  syncLanHost({ quiet });

  const timer = setInterval(() => {
    const { changed, url } = syncLanHost({ quiet: true });
    if (changed && !quiet) {
      console.log(`[lan-host] Network changed — Supabase API → ${url}`);
      console.log('[lan-host] Metro should hot-reload; if not, press r in the Expo terminal.');
    }
  }, intervalMs);

  return () => clearInterval(timer);
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];

if (isMain) {
  const watch = process.argv.includes('--watch');
  if (watch) {
    console.log('[lan-host] Watching for LAN IP changes…');
    startLanWatch({ quiet: false });
  } else {
    syncLanHost();
  }
}
